standard_lr : 0.01
momentum_val : 0.9
L2_penalty : 0.00001
sch_reduceLR_mode : "min"
sch_reduceLR_factor : 0.1
sch_reduceLR_patience : 10
sch_reduceLR_threshold : 0.0001
sch_reduceLR_threshold_mode : "abs"
sch_reduceLR_min_lr : 0
sch_reduceLR_cooldown : 0
sch_reduceLR_eps : 0.00000001
horizontalFlipProb : 0.2
shiftLimit : 0.1 
scaleLimit : 0.1
shiftScaleRotateProb : 0.25
maxHoles : 1 
minHoles : 1
maxHeight : 16 
maxWidth : 16
minHeight : 16
minWidth : 16
coarseDropoutProb : 0.5
grayscaleProb : 0.15
padHeightWidth : 40
randomCropSize : 32
randomCropProb : 1
rotateLimit : 5